name: "Terraform CI/CD"

on:
  push:
    paths:
      - 'infrastructure-live/**'
      - '.github/workflows/**'
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Install Terragrunt
      run: |
        curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.56.4/terragrunt_linux_amd64 -o terragrunt
        chmod +x terragrunt
        sudo mv terragrunt /usr/local/bin/

    - name: Run Terragrunt Apply
      run: |
        cd infrastructure-live/dev/ec2  # change to prod/ec2 as needed
        terragrunt init
        terragrunt apply -auto-approve

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2